name: Build and Test Quarkus Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Quarkus CLI with JBang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "export PATH=$PATH:~/.jbang/bin" >> $GITHUB_ENV

      - name: Download Maven dependencies
        run: |
          mvn -B dependency:go-offline

      - name: Build Quarkus application
        run: |
          mvn -B package -DskipTests -Dquarkus.package.type=uber-jar