name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Fazer o build da imagem Docker
      - name: Build Docker image
        run: docker build -t ozteps/cryptlink-api:latest .

      # Fazer login no Docker Hub
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Fazer push da imagem para o Docker Hub
      - name: Push Docker image
        run: docker push ozteps/cryptlink-api:latest