name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Fazer o build da imagem Docker
      - name: Build Docker image
        run: docker build -t ozteps/cryptlink-api:latest .

      # Fazer login no Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Fazer push da imagem para o Docker Hub
      - name: Push Docker image
        run: docker push ozteps/cryptlink-api:latest